[package]
name = "rustmission"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rm-config = { path = "../rm-config" }

anyhow = "1"
ratatui = "0.26"
tokio = { version = "1", features = ["rt", "macros", "sync"] }
tokio-util = "0.7"
crossterm = { version = "0.27", features = ["event-stream"] }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
transmission-rpc = "0.4.2"
tui-input = "0.8"
