[package]
name = "rm-color"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { version = "0.26.3", default-features = false }
serde = { version="1.0", features = ["derive"]}

[dev-dependencies]
serde_json = "1.0.117"
